package model.time;

public enum TimedOperationType {
    BUILD_TASK,
    UPGRADE_TASK,
    PRODUCTION_TASK,
    PURIFICATION_WATER_AND_SOIL_TASK,
    RANDOM_EVENT_TASK,
    TRAIN_ARMY_TASK,
    TRAVEL_TO_BATTLE_TASK,
    BATTLE_TASK,
    RETURN_FROM_BATTLE_TASK
}
